import { SkillNode } from './skillTreeUtils';
import {
  Code,
  Database,
  Globe,
  Layout,
  Server,
  Cpu,
  PaintBucket,
  Layers,
  Braces,
  FileJson,
  GitBranch,
  Workflow,
  BarChart3,
  Bot,
  Cloud,
  FileCode2,
  Puzzle,
  LineChart,
  Boxes,
  Laptop,
  Monitor,
  Smartphone,
  BarChart,
  Beaker,
  Container,
  GitCompare,
  Brain,
  Languages,
  Store,
} from 'lucide-react';

// Import technology-specific icons from react-icons/si
import {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNodedotjs,
  SiExpress,
  SiFlask,
  SiMysql,
  SiMongodb,
  SiGraphql,
  SiDocker,
  SiGithubactions,
  SiGit,
  SiTailwindcss,
  SiTensorflow,
  SiReact as SiReactNative,
  SiAmazon,
} from 'react-icons/si';

export const skillTreeData: SkillNode[] = [
  // Center/Core Node
  {
    id: 'dev',
    name: 'Software Development',
    icon: Cpu,
    level: 0,
    angle: 0, // Center node, angle doesn't matter
    connections: ['frontend', 'backend', 'tools', 'design', 'mobile'],
  },
  
  // Level 1 - Primary Skills
  {
    id: 'frontend',
    name: 'Frontend',
    icon: Layout,
    level: 1,
    angle: 0,
    connections: ['dev', 'react', 'javascript', 'css'],
  },
  {
    id: 'backend',
    name: 'Backend',
    icon: Server,
    level: 1,
    angle: 72,
    connections: ['dev', 'node', 'databases', 'api', 'python'],
  },
  {
    id: 'tools',
    name: 'Dev Tools',
    icon: Puzzle,
    level: 1,
    angle: 144,
    connections: ['dev', 'git', 'testing', 'build-tools', 'devops'],
  },
  {
    id: 'design',
    name: 'Design',
    icon: PaintBucket,
    level: 1,
    angle: 216,
    connections: ['dev', 'ui-ux', 'responsive'],
  },
  {
    id: 'mobile',
    name: 'Mobile & Desktop',
    icon: Smartphone,
    level: 1,
    angle: 288,
    connections: ['dev', 'mobile-frameworks'],
  },
  
  // Level 2 - Frontend Skills
  {
    id: 'react',
    name: 'React',
    icon: SiReact,
    level: 2,
    angle: 0,
    connections: ['frontend', 'nextjs', 'state-mgmt'],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: SiJavascript,
    level: 2,
    angle: 15,
    connections: ['frontend', 'typescript', 'vue'],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: SiTypescript,
    level: 2,
    angle: 30,
    connections: ['javascript'],
  },
  {
    id: 'css',
    name: 'CSS & Styling',
    icon: Layers,
    level: 2,
    angle: 345,
    connections: ['frontend', 'tailwind'],
  },
  
  // Level 2 - Backend Skills
  {
    id: 'node',
    name: 'Node.js',
    icon: SiNodedotjs,
    level: 2,
    angle: 60,
    connections: ['backend', 'express'],
  },
  {
    id: 'python',
    name: 'Python',
    icon: SiPython,
    level: 2,
    angle: 45,
    connections: ['backend', 'flask', 'ml'],
  },
  {
    id: 'databases',
    name: 'Databases',
    icon: Database,
    level: 2,
    angle: 75,
    connections: ['backend', 'sql', 'nosql'],
  },
  {
    id: 'api',
    name: 'API Design',
    icon: FileJson,
    level: 2,
    angle: 90,
    connections: ['backend', 'graphql'],
  },
  
  // Level 2 - Tools
  {
    id: 'git',
    name: 'Git & GitHub',
    icon: SiGit,
    level: 2,
    angle: 135,
    connections: ['tools'],
  },
  {
    id: 'testing',
    name: 'Testing',
    icon: Workflow,
    level: 2,
    angle: 150,
    connections: ['tools'],
  },
  {
    id: 'build-tools',
    name: 'Build Tools',
    icon: Boxes,
    level: 2,
    angle: 165,
    connections: ['tools'],
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: GitCompare,
    level: 2,
    angle: 180,
    connections: ['tools', 'docker', 'cicd'],
  },
  
  // Level 2 - Design
  {
    id: 'ui-ux',
    name: 'UI/UX Design',
    icon: Laptop,
    level: 2,
    angle: 210,
    connections: ['design'],
  },
  {
    id: 'responsive',
    name: 'Responsive Design',
    icon: BarChart3,
    level: 2,
    angle: 225,
    connections: ['design', 'data-viz'],
  },
  
  // Level 2 - Mobile & Desktop
  {
    id: 'mobile-frameworks',
    name: 'Mobile Frameworks',
    icon: Smartphone,
    level: 2,
    angle: 270,
    connections: ['mobile', 'react-native'],
  },
  
  // Level 3 - Advanced Skills
  {
    id: 'nextjs',
    name: 'Next.js',
    icon: SiNextdotjs,
    level: 3,
    angle: 0,
    connections: ['react'],
  },
  {
    id: 'vue',
    name: 'Vue.js',
    icon: SiVuedotjs,
    level: 3,
    angle: 15,
    connections: ['javascript'],
  },
  {
    id: 'state-mgmt',
    name: 'State Management',
    icon: Store,
    level: 3,
    angle: 30,
    connections: ['react'],
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    icon: SiTailwindcss,
    level: 3,
    angle: 345,
    connections: ['css'],
  },
  {
    id: 'express',
    name: 'Express.js',
    icon: SiExpress,
    level: 3,
    angle: 60,
    connections: ['node'],
  },
  {
    id: 'flask',
    name: 'Flask',
    icon: SiFlask,
    level: 3,
    angle: 45,
    connections: ['python'],
  },
  {
    id: 'sql',
    name: 'SQL',
    icon: SiMysql,
    level: 3,
    angle: 75,
    connections: ['databases'],
  },
  {
    id: 'nosql',
    name: 'NoSQL',
    icon: SiMongodb,
    level: 3,
    angle: 90,
    connections: ['databases'],
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    icon: SiGraphql,
    level: 3,
    angle: 105,
    connections: ['api'],
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: SiDocker,
    level: 3,
    angle: 165,
    connections: ['devops'],
  },
  {
    id: 'cicd',
    name: 'CI/CD Pipelines',
    icon: SiGithubactions,
    level: 3,
    angle: 180,
    connections: ['devops', 'cloud'],
  },
  {
    id: 'ml',
    name: 'Machine Learning',
    icon: SiTensorflow,
    level: 3,
    angle: 45,
    connections: ['python', 'nlp'],
  },
  {
    id: 'data-viz',
    name: 'Data Visualization',
    icon: BarChart,
    level: 3,
    angle: 225,
    connections: ['responsive'],
  },
  {
    id: 'nlp',
    name: 'NLP',
    icon: Brain,
    level: 3,
    angle: 60,
    connections: ['ml'],
  },
  {
    id: 'react-native',
    name: 'React Native',
    icon: SiReactNative,
    level: 3,
    angle: 270,
    connections: ['mobile-frameworks'],
  },
  {
    id: 'cloud',
    name: 'Cloud Services',
    icon: SiAmazon,
    level: 3,
    angle: 195,
    connections: ['cicd'],
  },
  {
    id: 'analytics',
    name: 'Analytics',
    icon: LineChart,
    level: 3,
    angle: 240,
    connections: ['data-viz'],
  },
]; 